services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - 8088:8088
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=css12345
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: css12345
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  mail-dev:
    container_name: mail-dev-css
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"


networks:
  spring-demo:
    driver: bridge

volumes:
  pgdata: {}
